# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Hayaku.QuickDash
PackageVersion: 0.5.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: quickdash.exe
  PortableCommandAlias: quickdash
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/iamtakingithard/QuickDash/releases/download/0.5.4/windows-msvc.zip
  InstallerSha256: A7DC3ADBD819AD7684EF1BF843010F552E056086EF21EB9747715D37FD22AEBE
ManifestType: installer
ManifestVersion: 1.6.0
